// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCheckout() {
  return window['go']['payment']['Payment']['CreateCheckout']();
}

export function OpenCheckoutBrowser(arg1) {
  return window['go']['payment']['Payment']['OpenCheckoutBrowser'](arg1);
}

export function Startup(arg1) {
  return window['go']['payment']['Payment']['Startup'](arg1);
}
