// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}
