// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {state} from '../models';

export function CheckLicense():Promise<void>;

export function GetState():Promise<state.AppState>;

export function IsLoggedIn():Promise<boolean>;
