// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {state} from '../models';

export function CheckDeviceFingerPrint(arg1:domain.LicenseClaims):Promise<void>;

export function CheckLicense():Promise<void>;

export function CheckLicenseTime(arg1:domain.LicenseClaims):Promise<void>;

export function GetState():Promise<state.AppState>;

export function IsLoggedIn():Promise<boolean>;

export function OnShutDown():Promise<void>;
