// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckDeviceFingerPrint(arg1) {
  return window['go']['main']['App']['CheckDeviceFingerPrint'](arg1);
}

export function CheckLicense() {
  return window['go']['main']['App']['CheckLicense']();
}

export function CheckLicenseTime(arg1) {
  return window['go']['main']['App']['CheckLicenseTime'](arg1);
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function IsLoggedIn() {
  return window['go']['main']['App']['IsLoggedIn']();
}
