// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Signin(arg1) {
  return window['go']['auth']['Auth']['Signin'](arg1);
}

export function Signup(arg1) {
  return window['go']['auth']['Auth']['Signup'](arg1);
}

export function Startup(arg1, arg2) {
  return window['go']['auth']['Auth']['Startup'](arg1, arg2);
}
