// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';
import {state} from '../models';
import {store} from '../models';

export function Signin(arg1:domain.LoginRequest):Promise<domain.LoginResponse>;

export function Signup(arg1:domain.LoginRequest):Promise<domain.LoginResponse>;

export function Startup(arg1:context.Context,arg2:state.AppState,arg3:store.Store):Promise<void>;
