// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecodeLicense(arg1) {
  return window['go']['license']['License']['DecodeLicense'](arg1);
}

export function Startup(arg1, arg2) {
  return window['go']['license']['License']['Startup'](arg1, arg2);
}
