// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['license']['License']['ActivateLicense'](arg1);
}

export function DecodeLicense(arg1) {
  return window['go']['license']['License']['DecodeLicense'](arg1);
}

export function GenerateLicense(arg1) {
  return window['go']['license']['License']['GenerateLicense'](arg1);
}

export function InitializeJournal() {
  return window['go']['license']['License']['InitializeJournal']();
}

export function Startup(arg1) {
  return window['go']['license']['License']['Startup'](arg1);
}

export function WriteJournalEntry(arg1, arg2) {
  return window['go']['license']['License']['WriteJournalEntry'](arg1, arg2);
}
