// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {context} from '../models';

export function ActivateLicense(arg1:string):Promise<void>;

export function DecodeLicense(arg1:domain.License):Promise<domain.LicenseClaims>;

export function GenerateLicense(arg1:domain.GenerateKeyRequest):Promise<domain.License>;

export function InitializeJournal():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
